routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('home.index');

Auth::routes();

Route::get('/dashboard', 'DashboardController@index')->name('dashboard');


Route::resource('post/{post}/category', 'PostCategoryController', ['as' => 'post'])->only(['create', 'store','destroy']);

Route::resource('post/{post}/comment', 'PostCommentController', ['as' => 'post'])->only(['store', 'update', 'destroy']);

Route::resource('post', 'PostController');

Route::resource('category', 'CategoryController');

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Repositories\PostCategoryRepositoryInterface;
use App\Repositories\PostRepositoryInterface;
use Illuminate\Http\Request;

class CategoryController extends Controller
{
    /**
     * Category repository
     *
     * @var PostCategoryRepositoryInterface
     */
    private $category_repository;

    /**
     * Post repository
     *
     * @var App\Repositories\PostRepositoryInterface
     */
    private $post_repository;

    /**
     * Class constructor
     *
     * @param PostCategoryRepositoryInterface   $category_repository    - Category repository
     * @param PostRepositoryInterface           $post_repository        - Post repository
     */
    public function __construct(
        PostCategoryRepositoryInterface $category_repository,
        PostRepositoryInterface $post_repository
    ) {
        $this->middleware('auth')->except(['index', 'show']);

        $this->category_repository = $category_repository;
        $this->post_repository = $post_repository;
    }

    /**
     * Display a listing of the resource.
     *
     * @param  \Illuminate\Http\Request  $request
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $filters = $this->getFilters($request);

        $categories = $this->category_repository->getAll($filters);

        return view('category.index', compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     *
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int                      $id
     *
     * @return \Illuminate\Http\Response
     */
    public function show(Request $request, $id)
    {
        $filters = $this->getFilters($request);

        $category = is_numeric($request->category) ? $this->category_repository->getById($request->category) : $this->category_repository->getBySlug($request->category);

        $posts = $this->post_repository->getAllPaginated($filters);

        return view('category.show', compact('category', 'posts'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     *
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int                      $id
     *
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     *
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/category/components/actions.blade.php
<div class="pull-right">
    <a href="{{ route('category.show', $category->slug) }}" class="btn btn-xs btn-default">
        Show
    </a>
</div>

resources/views/category/components/list.blade.php
<ul class="list-group">
    @forelse($categories as $category)
    <a href="{{ route('category.show', $category->slug) }}" class="list-group-item">
        @if (isset($post) and Auth::id() == $post->user_id)
            <div class="pull-right">
                @include('post.category.components.actions')
            </div>
        @endif

        {{ $category->name }}
    </a>
    @empty
    <li class="list-group-item">
        <p>No categories.</p>
    </li>
    @endforelse
    @if (isset($post) and Auth::id() == $post->user_id)
        <li class="list-group-item">
            <a href="{{ route('post.category.create', $post->slug) }}">Click here</a> to add a new one.
        </li>
    @endif
</ul>

resources/views/category/components/table.blade.php
<table class="table table-hover">
    <thead>
        <tr>
            <th>#</th>
            <th>Name</th>
            <th>Posts</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        @forelse($categories as $category)
            <tr>
                <td>{{ $category->id }}</td>
                <td>{{ $category->name }}</td>
                <td>{{ $category->posts()->count() }}</td>
                <td>@include('category.components.actions')</td>
            </tr>
        @empty
            <tr>
                <td colspan="4">No categories registered.</td>
            </tr>
        @endforelse
    </tbody>
</table>